#ifndef SCRATCHOS_LABGUAGE_H
#define SCRATCHOS_LABGUAGE_H

#define ERROR_MALLOC "allocation mémoire impossible\n"
#define ERROR_ACCESS_DISKFILE "Could not open diskFile\n"
#define ERROR_READ_SUPERBLOCK "A problem occured while reading the super block\n"
#define ERROR_READ_INODES_TABLE "A problem occured while reading the inodes table\n"
#define ERROR_READ_USERS_TABLE "A problem occured while reading the users table\n"
#define ERROR_WRITE_SUPERBLOCK "A problem occured while writing the super block\n"
#define ERROR_WRITE_BLOCK "A problem occured while writing the block\n"
#define ERROR_WRITE_INODES_TABLE "A problem occured while writing the inodes table\n"
#define ERROR_WRITE_USERS_TABLE "A problem occured while writing the users table\n"
#define ERROR_FILE_CLOSE "Cannot close file\n"
#define ERROR_FILE_OPEN "Cannot open file\n"
#define ERROR_FSEEK "Unable to change position\n"
#define ERROR_FTELL "Cannot get the file position\n"
#define ERROR_DISK_FULL "The disk storage is full.\n"
#define ERROR_FWRITE "An error occurred while writing block\n"
#define ERROR_READ "An error occurred while reading block\n"
#define ERROR_INODE_TABLE_FULL "The inode table is full.\n"
#define ERROR_INODE_INDEX "Incorrect index of inode\n"
#define ERROR_INODE_INIT "Inode not initialized\n"
#define ERROR_USER_ID "Incorrect userid\n"
#define ERROR_USER_MAX "Maximum amount of users is reached\n"
#define ERROR_USER_EXIST "User already exists\n"
#define ERROR_USER_INPUT "Reading user input error\n"
#define ERROR_COMMAND_LS_USAGE "Usage: ls [-l]\n"
#define ERROR_COMMAND_CAT_USAGE "Usage: cat <file name>\n"
#define ERROR_COMMAND_RM_USAGE "Usage: rm <file name>\n"
#define ERROR_COMMAND_CR_USAGE "Usage: cr <file name>\n"
#define ERROR_COMMAND_ARGS_UNKNOWN "Unknown argument\n"
#define ERROR_COMMAND_ARGS_FILE_EXIST "File does not exist: %s\n"
#define ERROR_FILE_RIGHTS "You aren't authorized to access this file\n"
#define OUTPUT_COMMAND_RM "%s deleted\n"
#define OUTPUT_COMMAND_CR "File %s created\n"
#define ERROR_COMMAND_EDIT_USAGE "Usage: edit <file name>\n"
#define OUTPUT_COMMAND_EDIT_EDITING "Editing %s (Enter to stop editing) :\n"
#define OUTPUT_COMMAND_EDIT_LINE "Line n°%d : "
#define ERROR_COMMAND_EDIT_INPUT_MAX "Your input may have been too long\n"
#define ERROR_COMMAND_EDIT_FILE_MAXSIZE "This file has reached its maximum size\n"
#define OUTPUT_COMMAND_EDIT_END "File %s edited\n"
#define ERROR_COMMAND_LOAD_USAGE "Usage: load <file name>\n"
#define ERROR_COMMAND_LOAD_LOADING_FILE "Error on loading file %s\n"
#define OUTPUT_COMMAND_LOAD "File %s loaded\n"
#define ERROR_COMMAND_STORE_USAGE "Usage: store <file name>\n"
#define ERROR_COMMAND_STORE_STORING_FILE "Error on storing file: %s\n"
#define OUTPUT_COMMAND_STORE "File %s stored\n"
#define ERROR_COMMAND_CHOWN_USAGE "Usage: chown <file name> <login>\n"
#define ERROR_COMMAND_ARGS_LOGIN_EXIST "Login does not exist: %s\n"
#define OUTPUT_COMMAND_CHOWN "Rights of %s changed from %s to %s\n"
#define ERROR_COMMAND_CHMOD_USAGE "Usage: chmod <file name> <right>\n"
#define ERROR_COMMAND_ARGS_RIGHT_EXIST "Those rights does not exist: %s\n"
#define OUTPUT_COMMAND_CHMOD "Rights of %s changed to %s\n"
#define ERROR_COMMAND_LISTEUSERS_USAGE "Usage: listusers\n"
#define OUTPUT_COMMAND_LISTUSERS "List of users: \n"
#define ERROR_COMMAND_ADDUSER_USAGE "Usage: adduser\n"
#define ERROR_COMMAND_ARGS_ROOT_ONLY "Only root user is allowed\n"
#define OUTPUT_COMMAND_ADDUSER_LOGIN "Please enter a login for the new user: \n"
#define OUTPUT_COMMAND_ADDUSER_PWD "Please enter a password for the new user: \n"
#define OUTPUT_COMMAND_ADDUSER_CREATED "New user created\n"
#define ERROR_COMMAND_RMUSER_USAGE "Usage: rmuser <login>\n"
#define OUTPUT_COMMAND_RMUSER "User %s removed\n"
#define ERROR_COMMAND_UNKNOWN "[%s] Unknown command \"%s\"\n"
#define ERROR_COMMAND_HELP_USAGE "Usage: help <command name>\n"
#define CONSOLE_LOGIN "login: \n"
#define CONSOLE_PWD "password: \n"
#define ERROR_OS_USAGE "[USAGE] %s disk_path"
#define OUTPUT_OS_STARTING_DISK "Starting disk...\n"
#define OUTPUT_OS_STARTING_SHELL "Starting shell...\n"
#define OUTPUT_OS_STOP_SHELL "Shell return with code %d\n"
#define OUTPUT_OS_SHUTDOWN "Shutting down...\n"


#endif //SCRATCHOS_LABGUAGE_H